@startuml
start
:"AbstractDataLoader";
:"定时任务相关设置，设置时间，线程";
:"读取本地文件，保存map";
:"检查版本和远端是否一致";
:"启动定时任务，主动去远端拉取最新版本（http））";
end
@end

@startuml
start
:"@Qconfig注解";
:"QConfigAnnotationProcessor 解析注解（反射））";
:"获取mapconfig，添加listener,赋值给被注解对象";
end
@end

@startuml
start
:"admin端（用户动态修改配置文件））";
:"通知对应的端重新去server获取最新文件";
:"修改本地文件值";
end
@enduml

